// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyuBhe1kT7TAOtXmf8j91oPXevzsYAjzg',
    appId: '1:670610732776:web:d661d9d05c990988b8fb5d',
    messagingSenderId: '670610732776',
    projectId: 'e-learing-fea85',
    authDomain: 'e-learing-fea85.firebaseapp.com',
    storageBucket: 'e-learing-fea85.firebasestorage.app',
    measurementId: 'G-5M1RSZYQJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNeajsmoYDrTDzdvk0dnJYOD_IL6SRQRE',
    appId: '1:670610732776:android:409654286eaa04c9b8fb5d',
    messagingSenderId: '670610732776',
    projectId: 'e-learing-fea85',
    storageBucket: 'e-learing-fea85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi-F4tEwAcC-7edQpS0_zIanpGP-Jwkj0',
    appId: '1:670610732776:ios:827bd912c68247d8b8fb5d',
    messagingSenderId: '670610732776',
    projectId: 'e-learing-fea85',
    storageBucket: 'e-learing-fea85.firebasestorage.app',
    iosBundleId: 'com.example.eLearningApp',
  );
}
